# Service Connection Mapping Configuration
# Maps subscription IDs to Azure DevOps Service Connection names
# If a subscription is not listed here, the default service connection from variable group will be used

subscriptions:
  - subscription_id: "sub-123"
    service_connection: "spn-prod-subscription-123"
  # Add more subscriptions as needed
  # - subscription_id: "sub-456"
  #   service_connection: "spn-prod-subscription-456"

